pipeline{
    agent any
    environment {
        DOCKER_IMAGE_NAME = 'calculator'
        GITHUB_REPO_URL = 'https://github.com/Manognya5/spe_miniproject.git'
    }
    stages{
        stage("Stage 1 : Git Clone"){
            steps{
                script {
                    git branch: 'main', url: "${GITHUB_REPO_URL}"
                }
            }
        }

        stage("Stage 2 : Maven Build"){
            steps{
                sh 'mvn -f calculator/pom.xml clean package'
            }
        }
        stage("Stage 3 : Maven Test"){
            steps{
                sh 'mvn -f calculator/pom.xml test'
            }
        }

        stage("Stage 4 : Build Docker Image"){
            steps{
               script {
                    docker.build("${DOCKER_IMAGE_NAME}", '--no-cache .')
                }
            }
        }

        stage("Stage 5 : Push Docker Image to Dockerhub"){
            steps{
                script {
                    docker.withRegistry('', 'DockerHubCred') {
                    sh 'docker tag calculator manognya5/calculator:latest'
                    sh 'docker push manognya5/calculator'
                }
            }
            }
        }

        stage('Stage 6 : Ansible Deployment') {
            steps {
                script {
                    ansiblePlaybook(
                    playbook: 'deploy.yml',
                    inventory: 'inventory.ini'
                    )
                }
             }
        }
    }
}

